export const API_ROUTES = {
    BASE_URL: 'https://dev.bunawat.com',
    API_VERSION: '/api'
}

export const API_URL = {
    adminLogin: "admin_login",
    addCustomer: "customer/add",
    editCustomer: "customer/update",
    addInfluencer: "influencer/add",
    editInfluencer: "influencer/update",
    getCustomers: "customer/getall",
    getResllers: "reseller/getall",
    addResller: "resller/add",
    editResller: "reseller/update",
    getInfluencers: "influencer/getall",
    deleteCustomers: "customer/remove",
    deleteResllers: "reseller/remove",
    deleteInfluencers: "influencer/remove",
    getCustomer: "customer",
    getResller: "reseller",
    getInfluencer: "influencer",
    getCollections: "collection/getall",
    getCollection: "collection",
    deleteCollection: "collection/remove",
    addCollection: "collection/add",
    editCollection: "collection/update",
    getParentCategorys: "parent_cateogry/getall",
    getParentCategory: "parent_cateogry",
    addParentCategory: "parent_cateogry/add",
    editParentCategory: "parent_cateogry/update",
    deleteParentCategory: "parent_cateogry/remove",
    getParentSubCategorys: "sub_category/getall",
    getParentSubCategory: "sub_category",
    addParentSubCategory: "sub_category/add",
    editParentSubCategory: "sub_category/update",
    deleteParentSubCategory: "sub_category/remove",
    getCategorys: "category/getall",
    getCategory: "category",
    addCategory: "category/add",
    editCategory: "category/update",
    deleteCategory: "category/remove",
    getAttributes: "attribute/getall",
    getAttribute: "attribute",
    addAttribute: "attribute/add",
    deleteAttribute: "attribute/remove",
    getVarients: "variant/getall",
    addVarient: "variant/add",
    deleteVarient: "variant/remove",
}